name: TreexBuyer
version: '${project.version}'
main: me.jetby.treexbuyer.Main
api-version: '1.16'
authors: [MrJetby]
website: https://treexstudio.site
commands:
  dummyCommand:
    description: "A placeholder command"